/*
 * This source file was generated by the Gradle 'init' task
 */
package visualiser;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageWriteParam;
import javax.imageio.ImageWriter;
import javax.imageio.stream.ImageOutputStream;

import graph.ContractionHierachy;

public class App {
    public static void main(String[] args) throws IOException {
        Scanner sc = new Scanner(System.in);
        var pr = ContractionHierachy.read(sc);
        long[] ids = pr.first;
        ContractionHierachy ch = pr.second;

        int width = Integer.parseInt(args[0]);
        int height = Integer.parseInt(args[1]);
        String path = args[2];

        BufferedImage image = Visualiser.visualise(width, height, ch, ids);
        writeImage(image, path, "png");
    }

    /**
     *
     * @param image        A buffered image to write
     * @param outputPath   The path where the images is written
     * @param outputFormat The image format
     */
    private static void writeImage(BufferedImage image, String path, String outputFormat)
            throws IOException {
        ImageWriter writer = ImageIO.getImageWritersByFormatName(outputFormat).next();
        ImageWriteParam param = writer.getDefaultWriteParam();
        param.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
        param.setCompressionQuality(0.5f); // Adjust the quality parameter as needed

        new File(path).mkdir();

        File fOutputFile = new File(path);
        ImageOutputStream ios = ImageIO.createImageOutputStream(fOutputFile);
        writer.setOutput(ios);
        writer.write(null, new IIOImage(image, null, null), param);
        writer.dispose();
        ios.close();
    }
}
